"""add_bidder_submission_kyc_fields

Revision ID: f18ed3fac32f
Revises: c0b3f1ab85f2
Create Date: 2026-05-14 12:49:42.410004

"""
from alembic import op
import sqlalchemy as sa


revision = 'f18ed3fac32f'
down_revision = 'c0b3f1ab85f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('bidders', sa.Column('submission_confirmed', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('bidders', sa.Column('submission_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('bidders', sa.Column('kyc_status', sa.String(length=10), nullable=True))
    op.add_column('bidders', sa.Column('kyc_run_at', sa.DateTime(), nullable=True))


def upgrade_DISABLED() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CRITERION_EXTRACTED', 'EVIDENCE_EXTRACTED', 'VERDICT_EMITTED', 'HUMAN_REVIEW_ASSIGNED', 'HUMAN_OVERRIDE_APPLIED', 'REPORT_EXPORTED', 'USER_LOGIN', 'CRITERION_SCHEMA_APPROVED', 'TENDER_UPLOADED', 'TENDER_DELETED', 'BIDDER_UPLOADED', 'BIDDER_REGISTERED', 'OCR_COMPLETED', 'BIDDER_DOC_VIEWED', 'DOCUMENT_DELETED', 'SUBMISSION_CONFIRMED', 'KYC_COMPLETED', name='auditeventtype'),
               existing_nullable=False)
    op.drop_index('ix_audit_events_tender_id', table_name='audit_events')
    op.drop_index('ix_audit_events_timestamp', table_name='audit_events')
    op.alter_column('bidder_documents', 'ocr_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='ocrstatus'),
               existing_nullable=True)
    op.drop_index('ix_bidder_documents_bidder_id', table_name='bidder_documents')
    op.drop_index('ix_bidder_evidence_bidder_id', table_name='bidder_evidence')
    op.drop_index('ix_bidder_evidence_criterion_id', table_name='bidder_evidence')
    op.add_column('bidders', sa.Column('submission_confirmed', sa.Boolean(), nullable=True))
    op.add_column('bidders', sa.Column('submission_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('bidders', sa.Column('kyc_status', sa.String(length=10), nullable=True))
    op.add_column('bidders', sa.Column('kyc_run_at', sa.DateTime(), nullable=True))
    op.alter_column('bidders', 'overall_verdict',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'NEEDS_MANUAL_REVIEW', 'PENDING', name='overallverdict'),
               existing_nullable=True)
    op.drop_index('ix_bidders_tender_id', table_name='bidders')
    op.alter_column('criterion_verdicts', 'verdict',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'NEEDS_MANUAL_REVIEW', name='verdictvalue'),
               existing_nullable=False)
    op.alter_column('criterion_verdicts', 'override_verdict',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'NEEDS_MANUAL_REVIEW', name='verdictvalue'),
               existing_nullable=True)
    op.drop_index('ix_criterion_verdicts_bidder_id', table_name='criterion_verdicts')
    op.drop_index('ix_document_chunks_doc_id', table_name='document_chunks')
    op.alter_column('review_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='reviewtaskstatus'),
               existing_nullable=True)
    op.alter_column('review_tasks', 'resolution_verdict',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'NEEDS_MANUAL_REVIEW', name='verdictvalue'),
               existing_nullable=True)
    op.drop_index('ix_review_tasks_bidder_id', table_name='review_tasks')
    op.alter_column('tender_criteria', 'category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('FINANCIAL', 'TECHNICAL', 'COMPLIANCE', 'COMPLETENESS', name='criterioncategory'),
               existing_nullable=False)
    op.alter_column('tender_criteria', 'mandatory_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('MANDATORY', 'OPTIONAL_PREFERRED', 'OPTIONAL_SCORED', 'CONDITIONAL', name='mandatorystatus'),
               existing_nullable=True)
    op.drop_index('ix_tender_criteria_tender_id', table_name='tender_criteria')
    op.alter_column('tenders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('UPLOADING', 'PROCESSING', 'CRITERIA_EXTRACTED', 'CRITERIA_APPROVED', 'EVALUATION_IN_PROGRESS', 'EVALUATION_COMPLETE', 'REPORT_GENERATED', name='tenderstatus'),
               existing_nullable=False)
    op.alter_column('tenders', 'ocr_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='ocrstatus'),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PROCUREMENT_OFFICER', 'SENIOR_OFFICER', 'SYSTEM_ADMIN', 'AUDIT_REVIEWER', 'BIDDER', name='userrole'),
               existing_nullable=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('bidders', 'kyc_run_at')
    op.drop_column('bidders', 'kyc_status')
    op.drop_column('bidders', 'submission_confirmed_at')
    op.drop_column('bidders', 'submission_confirmed')


def downgrade_DISABLED() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'role',
               existing_type=sa.Enum('PROCUREMENT_OFFICER', 'SENIOR_OFFICER', 'SYSTEM_ADMIN', 'AUDIT_REVIEWER', 'BIDDER', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('tenders', 'ocr_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='ocrstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('tenders', 'status',
               existing_type=sa.Enum('UPLOADING', 'PROCESSING', 'CRITERIA_EXTRACTED', 'CRITERIA_APPROVED', 'EVALUATION_IN_PROGRESS', 'EVALUATION_COMPLETE', 'REPORT_GENERATED', name='tenderstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index('ix_tender_criteria_tender_id', 'tender_criteria', ['tender_id'], unique=False)
    op.alter_column('tender_criteria', 'mandatory_status',
               existing_type=sa.Enum('MANDATORY', 'OPTIONAL_PREFERRED', 'OPTIONAL_SCORED', 'CONDITIONAL', name='mandatorystatus'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('tender_criteria', 'category',
               existing_type=sa.Enum('FINANCIAL', 'TECHNICAL', 'COMPLIANCE', 'COMPLETENESS', name='criterioncategory'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.create_index('ix_review_tasks_bidder_id', 'review_tasks', ['bidder_id'], unique=False)
    op.alter_column('review_tasks', 'resolution_verdict',
               existing_type=sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'NEEDS_MANUAL_REVIEW', name='verdictvalue'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('review_tasks', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='reviewtaskstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.create_index('ix_document_chunks_doc_id', 'document_chunks', ['doc_id'], unique=False)
    op.create_index('ix_criterion_verdicts_bidder_id', 'criterion_verdicts', ['bidder_id'], unique=False)
    op.alter_column('criterion_verdicts', 'override_verdict',
               existing_type=sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'NEEDS_MANUAL_REVIEW', name='verdictvalue'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('criterion_verdicts', 'verdict',
               existing_type=sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'NEEDS_MANUAL_REVIEW', name='verdictvalue'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.create_index('ix_bidders_tender_id', 'bidders', ['tender_id'], unique=False)
    op.alter_column('bidders', 'overall_verdict',
               existing_type=sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'NEEDS_MANUAL_REVIEW', 'PENDING', name='overallverdict'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('bidders', 'kyc_run_at')
    op.drop_column('bidders', 'kyc_status')
    op.drop_column('bidders', 'submission_confirmed_at')
    op.drop_column('bidders', 'submission_confirmed')
    op.create_index('ix_bidder_evidence_criterion_id', 'bidder_evidence', ['criterion_id'], unique=False)
    op.create_index('ix_bidder_evidence_bidder_id', 'bidder_evidence', ['bidder_id'], unique=False)
    op.create_index('ix_bidder_documents_bidder_id', 'bidder_documents', ['bidder_id'], unique=False)
    op.alter_column('bidder_documents', 'ocr_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='ocrstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.create_index('ix_audit_events_timestamp', 'audit_events', ['timestamp'], unique=False)
    op.create_index('ix_audit_events_tender_id', 'audit_events', ['tender_id'], unique=False)
    op.alter_column('audit_events', 'event_type',
               existing_type=sa.Enum('CRITERION_EXTRACTED', 'EVIDENCE_EXTRACTED', 'VERDICT_EMITTED', 'HUMAN_REVIEW_ASSIGNED', 'HUMAN_OVERRIDE_APPLIED', 'REPORT_EXPORTED', 'USER_LOGIN', 'CRITERION_SCHEMA_APPROVED', 'TENDER_UPLOADED', 'TENDER_DELETED', 'BIDDER_UPLOADED', 'BIDDER_REGISTERED', 'OCR_COMPLETED', 'BIDDER_DOC_VIEWED', 'DOCUMENT_DELETED', 'SUBMISSION_CONFIRMED', 'KYC_COMPLETED', name='auditeventtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
